name: Publish

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short=7 ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Update gradle.properties with short SHA
        run: |
          sed -i "s/module_version.*/module_version=alpha-${{ steps.vars.outputs.SHORT_SHA }}/" gradle.properties
          cat gradle.properties

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: current

      - name: Build with Gradle
        run: gradle build

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: h0Ef1dOf
          name: alpha-${{ steps.vars.outputs.SHORT_SHA }}
          version: alpha-${{ steps.vars.outputs.SHORT_SHA }}
          changelog: |
            ## ${{ github.event.head_commit.message }} 
            ðŸ‘¤ Change pushed by ${{ github.event.head_commit.author.name }}
            **ðŸ”— URL:** [View Commit](${{ github.event.head_commit.url }})
            *ðŸ¤– Automatic release from commit* `${{ github.sha }}`
          loaders: |-
            velocity
          dependencies: |-
            [{
              "project_id": "Hd02Faj9",
              "dependency_type": "required"
            },
            {
              "project_id": "b227Xhmj",
              "dependency_type": "required"
            }]
          game-versions: |-
            1.20.x
            1.21.x
          files: build/libs/rcs-pterodactyl-alpha-${{ steps.vars.outputs.SHORT_SHA }}.jar
